#!/usr/bin/env python3
"""Bake exact HarfBuzz advance widths for every on-screen string.

The film is laid out on explicit SVG coordinates, so text placement must be
deterministic in three places at once: the Remotion browser render, the
librsvg QA rasteriser, and the overlap checks. Measuring every string in
COPY with the real brand fonts (the same HarfBuzz shaping both engines use)
and baking the result into textMetrics.ts gives all three identical numbers.

Run from video/:  python3 tools/make-metrics.py
"""
import json
import re
import sys
from pathlib import Path

import uharfbuzz as hb
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONTS = {
    "sans800": ROOT / "public/fonts/plus-jakarta-sans-800.ttf",
    "sans700": ROOT / "public/fonts/plus-jakarta-sans-700.ttf",
    "sans500": ROOT / "public/fonts/plus-jakarta-sans-500.ttf",
    "mono400": ROOT / "public/fonts/jetbrains-mono-400.ttf",
}

# Extra strings used on screen that are not literals in copy.ts.
EXTRA = [
    "01", "02", "03", "04",
    "·", "→", "—",
    "culler",
    "SOL", "RH",
    # strings composed on screen rather than stored whole in COPY
    "HAS LEFTOVERS", ".", "+6",
    "BASE 100 PTS", "CLOSE_EMPTY_TOKEN_ACCOUNT", "VERIFIED",
]


def strings_from_copy() -> list[str]:
    import json as _json

    dump = ROOT / "tools/_copy-strings.json"
    if not dump.exists():
        raise SystemExit("run: node tools/dump-copy-strings.mjs first")
    return _json.loads(dump.read_text())


def main() -> None:
    strings = strings_from_copy() + EXTRA
    # de-dup, keep order
    seen: set[str] = set()
    unique: list[str] = []
    for s in strings:
        if s not in seen:
            seen.add(s)
            unique.append(s)

    fonts = {k: TTFont(str(p), lazy=True) for k, p in FONTS.items()}
    upems = {k: f["head"].unitsPerEm for k, f in fonts.items()}
    faces = {k: hb.Face(hb.Blob.from_file_path(str(p))) for k, p in FONTS.items()}
    hfonts = {k: hb.Font(f) for k, f in faces.items()}

    table: dict[str, dict[str, float]] = {}
    for s in unique:
        row: dict[str, float] = {}
        for k, hfont in hfonts.items():
            buf = hb.Buffer()
            buf.add_str(s)
            buf.guess_segment_properties()
            hb.shape(hfont, buf)
            adv = sum(p.position[2] for p in buf.glyph_positions)
            row[k] = round(adv / upems[k], 6)
        table[s] = row

    for f in fonts.values():
        f.close()

    out = ROOT / "src/brand/textMetrics.ts"
    lines = []
    lines.append("/**")
    lines.append(" * Exact advance widths (in em) for every on-screen string, shaped with")
    lines.append(" * HarfBuzz against the real CULLER brand fonts. Generated by")
    lines.append(" * tools/make-metrics.py — do not hand-edit.")
    lines.append(" *")
    lines.append(" * measure() returns pixel width = em * fontSize. Both the Remotion render and")
    lines.append(" * the librsvg QA rasteriser shape text with HarfBuzz, so layouts computed")
    lines.append(" * here are identical in both.")
    lines.append(" */")
    lines.append("")
    lines.append("export type TextStyleKey = 'sans800' | 'sans700' | 'sans500' | 'mono400';")
    lines.append("")
    lines.append("const W: Record<string, Record<TextStyleKey, number>> = " + json.dumps(table, ensure_ascii=False, separators=(",", ":")) + ";")
    lines.append("")
    lines.append("const FALLBACK: Record<TextStyleKey, number> = {")
    lines.append("  sans800: 0.62,")
    lines.append("  sans700: 0.6,")
    lines.append("  sans500: 0.55,")
    lines.append("  mono400: 0.6,")
    lines.append("};")
    lines.append("")
    lines.append("/** Pixel width of `text` at `size` px in the given brand style. */")
    lines.append("export function measure(text: string, style: TextStyleKey, size: number): number {")
    lines.append("  const row = W[text];")
    lines.append("  const em = row ? row[style] : text.split('').reduce((acc, ch) => acc + (W[ch]?.[style] ?? FALLBACK[style]), 0);")
    lines.append("  return em * size;")
    lines.append("}")
    lines.append("")
    lines.append("/** Em advance, for letter-spacing-aware composition. */")
    lines.append("export function measureEm(text: string, style: TextStyleKey): number {")
    lines.append("  const row = W[text];")
    lines.append("  if (row) return row[style];")
    lines.append("  return text.split('').reduce((acc, ch) => acc + (W[ch]?.[style] ?? FALLBACK[style]), 0);")
    lines.append("}")
    lines.append("")
    lines.append("/** Advance width including SVG letter-spacing (applied after every glyph). */")
    lines.append("export function measureTracked(text: string, style: TextStyleKey, size: number, trackingEm: number): number {")
    lines.append("  return measure(text, style, size) + trackingEm * size * text.length;")
    lines.append("}")
    lines.append("")
    lines.append("export const MEASURED_STRINGS = Object.keys(W);")
    lines.append("")
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(ROOT)}: {len(unique)} strings × {len(FONTS)} styles")


if __name__ == "__main__":
    sys.exit(main())
