/**
 * Runs the full Phase 4 Part F matrix (population sizes x participation
 * scenarios) through the deterministic economic simulator and writes a
 * markdown report. Pure computation only — no network, no DB, no
 * randomness beyond the fixed seed baked into economicSimulation.ts.
 *
 * Usage: npx tsx scripts/economic-simulations.ts
 */
import { writeFileSync } from "fs";
import { join } from "path";
import { ALL_SCENARIOS, runEmissionReport, EmissionReport } from "../src/lib/cull/economicSimulation";

const POPULATION_SIZES = [100, 1_000, 10_000, 100_000];
const REWARD_POOL = 1_000_000; // a fixed hypothetical pool; only the relative shares matter here

const pct = (n: number) => `${(n * 100).toFixed(2)}%`;
const num = (n: number) => n.toLocaleString(undefined, { maximumFractionDigits: 2 });

function assertInvariants(report: EmissionReport) {
  if (report.totalEmissions > report.rewardPool + 1e-6) {
    throw new Error(
      `INVARIANT VIOLATED: ${report.scenario} @ ${report.populationSize} wallets emitted ${report.totalEmissions}, exceeding the pool of ${report.rewardPool}.`
    );
  }
}

function scenarioDescription(scenario: string): string {
  switch (scenario) {
    case "LOW_PARTICIPATION":
      return "Only ~5% of the population culls anything (1 action each).";
    case "NORMAL_PARTICIPATION":
      return "~40% of the population participates, doing 1-3 real closes each.";
    case "HIGH_PARTICIPATION":
      return "~85% of the population is actively cleaning up, 1-8 closes each.";
    case "ONE_HEAVY_FARMER":
      return "Normal-participation background, plus one wallet with 5,000 closes.";
    case "MANY_SYBIL_WALLETS":
      return "80% normal-participation background + 20% single-action sybil wallets.";
    case "MIXED_LEGIT_AND_FARMING":
      return "Normal background + ~1% concentrated farmer wallets + ~10% sybil wallets.";
    default:
      return "";
  }
}

const lines: string[] = [];
lines.push("# CULLER Phase 4 — Economic simulation report");
lines.push("");
lines.push(
  "Deterministic, pure-function simulations of the points -> reward-pool formula " +
    "(`walletPoints / totalValidPoints * rewardPool`) across population sizes and " +
    "participation patterns. **Purpose: understand emission behavior, not optimize " +
    "toward a desired price.** No real $CULLER exists; `rewardPool` here is a fixed " +
    "hypothetical value (1,000,000) used only so relative shares and concentration " +
    "are comparable across scenarios."
);
lines.push("");
lines.push(`Generated by \`scripts/economic-simulations.ts\`. Reward pool used: ${num(REWARD_POOL)}.`);
lines.push("");

for (const scenario of ALL_SCENARIOS) {
  lines.push(`## ${scenario}`);
  lines.push("");
  lines.push(scenarioDescription(scenario));
  lines.push("");
  lines.push(
    "| Population | Active wallets | Active share | Avg points | Median points | Total emissions | Top wallet share | Top 10 share | Top 1% share | Sybil share | Farmer share |"
  );
  lines.push("|---|---|---|---|---|---|---|---|---|---|---|");

  for (const size of POPULATION_SIZES) {
    const report = runEmissionReport(scenario, size, REWARD_POOL);
    assertInvariants(report);
    lines.push(
      `| ${num(size)} | ${num(report.activeWallets)} | ${pct(report.activeShare)} | ${num(report.averagePoints)} | ${num(
        report.medianPoints
      )} | ${num(report.totalEmissions)} | ${pct(report.topWalletShare)} | ${pct(report.top10Share)} | ${pct(
        report.top1PercentShare
      )} | ${report.sybilShare > 0 ? pct(report.sybilShare) : "—"} | ${report.farmerShare > 0 ? pct(report.farmerShare) : "—"} |`
    );
  }
  lines.push("");
}

lines.push("## Observations");
lines.push("");
lines.push(
  "- **Total emissions never exceed the reward pool** in any run above (enforced both by " +
    "`simulateEpochRewards`'s remainder-absorption math and by the assertion this script runs " +
    "after every scenario)."
);
lines.push(
  "- **Concentration is a function of behavior, not population size.** LOW/NORMAL/HIGH " +
    "participation stay broadly distributed (low top-wallet/top-10 share) regardless of whether " +
    "there are 100 or 100,000 wallets, because every wallet follows the same random activity " +
    "distribution — scale alone doesn't fix or worsen fairness."
);
lines.push(
  "- **A single heavy farmer can dominate a pool** under the current flat, unlimited " +
    "points-per-action model: one wallet with thousands of its own empty accounts captures the " +
    "large majority of the pool in `ONE_HEAVY_FARMER`, at every population size. This is a " +
    "real, expected consequence of 'no reputation/streak scoring, pure proportional points' " +
    "(explicitly required for Phase 3) combined with no per-wallet-per-epoch cap (not yet built) " +
    "— worth deciding on deliberately, not something this simulation tries to hide or fix."
);
lines.push(
  "- **A sybil cluster's combined share is non-trivial even though each wallet looks like an " +
    "ordinary light user.** In `MANY_SYBIL_WALLETS`, 20% of wallets (all 1-action, indistinguishable " +
    "individually from genuine light users) collectively claim a meaningful slice of the pool " +
    "purely through numbers — this is the quantitative case for the anti-farming work already " +
    "flagged as architecture-only in Phase 3 (cross-wallet clustering, self-created-asset checks)."
);
lines.push(
  "- **Mixed realistic adversarial conditions compound.** `MIXED_LEGIT_AND_FARMING` shows farmer " +
    "and sybil shares both eating into the pool simultaneously, which is the more plausible " +
    "real-world risk shape than either extreme alone."
);
lines.push("");

const outPath = join(__dirname, "..", "docs", "economic-simulation-report.md");
writeFileSync(outPath, lines.join("\n") + "\n", "utf8");
console.log(`Wrote ${outPath}`);
